import {
  avatar1,
  avatar2,
  avatar3,
  avatar4,
  avatar5,
  avatar6,
  avatar7,
  discord,
  instagram,
  netflix,
  spotify,
  tiktok,
  twitter,
  youtubeThumbnail,
} from "@/assets";
import { CommentProps, VideoProps } from "@/types/types";

const dummyComments: CommentProps[] = [
  {
    name: "Fadekemi Adebayo",
    avatar: avatar2,
    content: "Great video! Very informative.",
    timestamp: "12 weeks ago",
    likes: 24,
    dislikes: 2,
    replies: [
      {
        name: "Marilyn Ata",
        avatar: avatar5,
        content: "You are very right!",
        timestamp: "12 weeks ago",
        likes: 1,
        dislikes: 0,
      },
    ],
  },
  {
    name: "Maria Garcia",
    avatar: avatar3,
    content: "Just Subscribed! Would love to learn more",
    timestamp: "6 months ago",
    likes: 24,
    dislikes: 3,
  },
  {
    name: "John Frazer",
    avatar: avatar4,
    content: "Great tutorial, easy to follow.",
    timestamp: "12 months ago",
    likes: 30,
    dislikes: 1,
  },
  {
    name: "Michaela Rodriguez",
    avatar: avatar7,
    content: "This is exactly what I needed, thanks!",
    timestamp: "10 minutes ago",
    likes: 75,
    dislikes: 3,
  },
  {
    name: "Marilyn Ata",
    avatar: avatar5,
    content: "You are very right!",
    timestamp: "12 weeks ago",
    likes: 1,
    dislikes: 0,
  },
  {
    name: "Alice Green",
    avatar: avatar5,
    content: "I love this list! My favorite genre.",
    timestamp: "1 month ago",
    likes: 80,
    dislikes: 1,
  },
  {
    name: "Jane Smith",
    avatar: avatar3,
    content: "Looking forward to the next part!",
    timestamp: "7 days ago",
    likes: 12,
    dislikes: 0,
  },
  {
    name: "Olivia Blaze",
    avatar: avatar6,
    content: "So cute! Made my day.",
    timestamp: "5 hours ago",
    likes: 64,
    dislikes: 14,
  },
  {
    name: "Francis Robinson",
    avatar: avatar2,
    content: "Great explanation! Really helped me understand closures.",
    timestamp: "2 weeks ago",
    likes: 100,
    dislikes: 2,
    replies: [
      {
        name: "Jane Smith",
        avatar: avatar3,
        content: "I agree! This was super helpful.",
        timestamp: "7 days ago",
        likes: 50,
        dislikes: 1,
      },
    ],
  },
  {
    name: "Marilyn Ata",
    avatar: avatar5,
    content: "This was so easy to understand. Thank you for explaining!",
    timestamp: "10 days ago",
    likes: 100,
    dislikes: 0,
  },
  {
    name: "Victor Williams",
    avatar: avatar6,
    content: "Confusing, needs better explanation.",
    timestamp: "4 days ago",
    likes: 3000,
    dislikes: 100,
  },
  {
    name: "Sofia Hernandez",
    avatar: avatar7,
    content: "Really enjoyed this review, thanks.",
    timestamp: "yesterday",
    likes: 34,
    dislikes: 1,
  },
  {
    name: "Olu Jacob",
    avatar: avatar1,
    content: "Finally understand, thanks for explaining.",
    timestamp: "13 hours ago",
    likes: 92,
    dislikes: 9,
  },
  {
    name: "Christopher Robinson",
    avatar: avatar2,
    content: "Learning so much, keep posting!",
    timestamp: "2 hours ago",
    likes: 320,
    dislikes: 2,
  },
  {
    name: "Simone Ashley",
    avatar: avatar3,
    content: "Disappointed, not what I expected.",
    timestamp: "5 days ago",
    likes: 2,
    dislikes: 32,
  },
  {
    name: "Bob Smith",
    avatar: avatar4,
    content: "This concept is much clearer now.",
    timestamp: "6 days ago",
    likes: 200,
    dislikes: 3
  }
];

const videos: VideoProps[] = [
  {
    title: "Understanding JavaScript Closures",
    channelName: "Code Academy",
    channelAvatar: avatar1,
    views: 450000,
    datePosted: "2 weeks ago",
    thumbnail: discord,
    description:
      "In this video, we delve deep into the concept of closures in JavaScript.",
    likes: 23000,
    dislikes: 300,
    duration: "12:45",
    tags: ["JavaScript", "Programming", "Web Development"],
    subscribers: 750000,
    comments: [
      {
        name: "John Doe",
        avatar: avatar2,
        content: "Great explanation! Really helped me understand closures.",
        timestamp: "2 weeks ago",
        likes: 100,
        dislikes: 2,
        replies: [
          {
            name: "Jane Smith",
            avatar: avatar3,
            content: "I agree! This was super helpful.",
            timestamp: "7 days ago",
            likes: 50,
            dislikes: 1,
          },
        ],
      },
      {
        name: "Marilyn Ata",
        avatar: avatar5,
        content: "This was so easy to understand. Thank you for explaining!",
        timestamp: "10 days ago",
        likes: 100,
        dislikes: 0,
      },
    ],
  },
  {
    title: "Top 10 Romantic Comedies to Watch",
    channelName: "Neso Academy",
    channelAvatar: avatar4,
    views: 320000,
    datePosted: "2 months ago",
    thumbnail: instagram,
    description: "A countdown of the top 10 romantic comedies you must watch.",
    likes: 18000,
    dislikes: 200,
    duration: "15:30",
    tags: ["Movies", "Romantic Comedies", "Entertainment"],
    subscribers: 500000,
    comments: [
      {
        name: "Alice Green",
        avatar: avatar5,
        content: "I love this list! My favorite genre.",
        timestamp: "1 month ago",
        likes: 80,
        dislikes: 1,
      },
      {
        name: "Jane Smith",
        avatar: avatar3,
        content: "Looking forward to the next part!",
        timestamp: "7 days ago",
        likes: 12,
        dislikes: 0,
      },
      {
        name: "Olivia Blaze",
        avatar: avatar6,
        content: "So cute! Made my day.",
        timestamp: "5 hours ago",
        likes: 64,
        dislikes: 14,
      },
      {
        name: "Michaela Rodriguez",
        avatar: avatar7,
        content: "This is exactly what I needed, thanks!",
        timestamp: "10 minutes ago",
        likes: 75,
        dislikes: 3,
      },
    ],
  },
  {
    title: "Introduction to Rust Programming",
    channelName: "Let's get Rusty",
    channelAvatar: avatar6,
    views: 150000,
    datePosted: "3 days ago",
    thumbnail: youtubeThumbnail,
    description: "A beginner's guide to Rust programming.",
    likes: 8000,
    dislikes: 50,
    duration: "12:30",
    tags: ["Rust", "Programming", "Beginner"],
    subscribers: 100000,
    comments: dummyComments
  },
  {
    title: "Learn JavaScript in 30 Minutes",
    channelName: "Code Academy",
    channelAvatar: avatar1,
    views: 150000,
    datePosted: "14 months ago",
    thumbnail: netflix,
    description: "A quick guide to learning JavaScript.",
    likes: 1200,
    dislikes: 50,
    duration: "30:00",
    tags: ["JavaScript"],
    subscribers: 500000,
    comments: [
      {
        name: "Fadekemi Adebayo",
        avatar: avatar2,
        content: "Great video! Very informative.",
        timestamp: "12 weeks ago",
        likes: 24,
        dislikes: 2,
        replies: [
          {
            name: "Marilyn Ata",
            avatar: avatar5,
            content: "You are very right!",
            timestamp: "12 weeks ago",
            likes: 1,
            dislikes: 0,
          },
        ],
      },
      {
        name: "Maria Garcia",
        avatar: avatar3,
        content: "Just Subscribed! Would love to learn more",
        timestamp: "6 months ago",
        likes: 24,
        dislikes: 3,
      },
      {
        name: "John Frazer",
        avatar: avatar4,
        content: "Great tutorial, easy to follow.",
        timestamp: "12 months ago",
        likes: 30,
        dislikes: 1,
      },
    ],
  },
  {
    title: "Top 10 Music Hits of 2023",
    channelName: "Neso Academy",
    channelAvatar: avatar5,
    views: 200000,
    datePosted: "1 year ago",
    thumbnail: spotify,
    description: "The best music hits of the year.",
    likes: 1800,
    dislikes: 30,
    duration: "15:00",
    tags: ["Music"],
    subscribers: 800000,
    comments: dummyComments,
  },
  {
    title: "Best Romantic Comedies to Watch",
    channelName: "Neso Academy",
    channelAvatar: avatar6,
    views: 100000,
    datePosted: "2 days ago",
    thumbnail: tiktok,
    description: "A list of the best romantic comedies.",
    likes: 900,
    dislikes: 20,
    duration: "20:00",
    tags: ["Romantic Comedies"],
    subscribers: 300000,
    comments: dummyComments,
  },
  {
    title: "Introduction to Databases",
    channelName: "Tech Guru",
    channelAvatar: avatar7,
    views: 120000,
    datePosted: "8 months ago",
    thumbnail: twitter,
    description: "Learn the basics of databases.",
    likes: 1100,
    dislikes: 40,
    duration: "25:00",
    tags: ["Databases"],
    subscribers: 400000,
    comments: dummyComments,
  },
  {
    title: "Rust Ownership and Borrowing",
    channelName: "Let's get Rusty",
    channelAvatar: avatar1,
    views: 95000,
    datePosted: "1 week ago",
    thumbnail: discord,
    description: "Understanding ownership and borrowing in Rust.",
    likes: 5000,
    dislikes: 20,
    duration: "15:00",
    tags: ["Rust", "Programming", "Advanced"],
    subscribers: 100000,
    comments: dummyComments
  },
  {
    title: "Top 10 Mobile Apps of 2024",
    channelName: "ckmobile",
    channelAvatar: avatar3,
    views: 200000,
    datePosted: "5 days ago",
    thumbnail: instagram,
    description: "A countdown of the top 10 mobile apps in 2024.",
    likes: 9000,
    dislikes: 30,
    duration: "20:00",
    tags: ["Mobile", "Apps", "Top 10"],
    subscribers: 150000,
    comments: [
      {
        name: "Charlie Johnson",
        avatar: avatar4,
        content: "Great list! Found some new apps to try.",
        timestamp: "4 days ago",
        likes: 400,
        dislikes: 6
      },
      ...(dummyComments)
    ]
  },
  {
    title: "CS50 2024 - Lecture 1",
    channelName: "CS50",
    channelAvatar: avatar5,
    views: 300000,
    datePosted: "1 month ago",
    thumbnail: netflix,
    description: "The first lecture of the 2024 CS50 course.",
    likes: 15000,
    dislikes: 70,
    duration: "1:30:00",
    tags: ["CS50", "Lecture", "Computer Science"],
    subscribers: 200000,
    comments: [
      {
        name: "Eve Adams",
        avatar: avatar6,
        content: "Excited to start this course!",
        timestamp: "29 days ago",
        likes: 500,
        dislikes: 0
      },
      ...(dummyComments)
    ]
  },
  {
    title: "Data Structures - Introduction",
    channelName: "Neso Academy",
    channelAvatar: avatar7,
    views: 250000,
    datePosted: "2 months ago",
    thumbnail: spotify,
    description: "An introduction to data structures.",
    likes: 12000,
    dislikes: 50,
    duration: "25:00",
    tags: ["Data Structures", "Computer Science", "Education"],
    subscribers: 180000,
    comments: dummyComments
  },
  {
    title: "Morning Prayer Routine",
    channelName: "Hallow: Prayer & Meditation",
    channelAvatar: avatar1,
    views: 80000,
    datePosted: "2 days ago",
    thumbnail: tiktok,
    description: "Start your day with this calming morning prayer routine.",
    likes: 4000,
    dislikes: 10,
    duration: "10:00",
    tags: ["Prayer", "Meditation", "Morning Routine"],
    subscribers: 90000,
    comments: dummyComments
  },
  {
    title: "Setting Up a Modern JavaScript Project",
    channelName: "No Boilerplate",
    channelAvatar: avatar2,
    views: 110000,
    datePosted: "1 week ago",
    thumbnail: twitter,
    description: "Learn how to set up a modern JavaScript project without boilerplate.",
    likes: 5000,
    dislikes: 15,
    duration: "20:00",
    tags: ["JavaScript", "Project Setup", "No Boilerplate"],
    subscribers: 130000,
    comments: dummyComments
  },
  {
    title: "JavaScript Arrays Explained",
    channelName: "Code Academy",
    channelAvatar: avatar3,
    views: 140000,
    datePosted: "3 days ago",
    thumbnail: youtubeThumbnail,
    description: "Deep dive into JavaScript arrays and their methods.",
    likes: 7000,
    dislikes: 30,
    duration: "12:00",
    tags: ["JavaScript", "Arrays", "Programming"],
    subscribers: 160000,
    comments: dummyComments
  },
  {
    title: "Best Android Tips and Tricks",
    channelName: "ckmobile",
    channelAvatar: avatar4,
    views: 120000,
    datePosted: "2 weeks ago",
    thumbnail: discord,
    description: "Learn some of the best tips and tricks for Android devices.",
    likes: 6000,
    dislikes: 25,
    duration: "18:00",
    tags: ["Mobile", "Android", "Tips"],
    subscribers: 150000,
    comments: dummyComments
  },
  {
    title: "CS50 2024 - Problem Set 1 Walkthrough",
    channelName: "CS50",
    channelAvatar: avatar5,
    views: 180000,
    datePosted: "3 weeks ago",
    thumbnail: instagram,
    description: "A detailed walkthrough of Problem Set 1.",
    likes: 9000,
    dislikes: 40,
    duration: "45:00",
    tags: ["CS50", "Problem Set", "Computer Science"],
    subscribers: 200000,
    comments: [
      {
        name: "Frank Miller",
        avatar: "path/to/avatar6.jpg",
        content: "This walkthrough really helped me understand the problems.",
        timestamp: "20 days ago",
        likes: 350,
        dislikes: 5
      },
      ...(dummyComments)
    ]
  },
  {
    title: "Operating Systems - Processes",
    channelName: "Neso Academy",
    channelAvatar: avatar6,
    views: 170000,
    datePosted: "1 month ago",
    thumbnail: netflix,
    description: "Understanding processes in operating systems.",
    likes: 8000,
    dislikes: 35,
    duration: "30:00",
    tags: ["Operating Systems", "Computer Science", "Education"],
    subscribers: 180000,
    comments: dummyComments
  },
  {
    title: "Evening Meditation for Relaxation",
    channelName: "Hallow: Prayer & Meditation",
    channelAvatar: avatar7,
    views: 60000,
    datePosted: "4 days ago",
    thumbnail: spotify,
    description: "Relax and unwind with this evening meditation session.",
    likes: 3000,
    dislikes: 8,
    duration: "15:00",
    tags: ["Meditation", "Relaxation", "Evening Routine"],
    subscribers: 90000,
    comments: [
      {
        name: "Jackie Robinson",
        avatar: avatar1,
        content: "Perfect way to end the day. So relaxing.",
        timestamp: "3 days ago",
        likes: 120,
        dislikes: 1
      },
      ...(dummyComments)
    ]
  },
  {
    title: "Clean Code Practices for JavaScript",
    channelName: "No Boilerplate",
    channelAvatar: avatar2,
    views: 90000,
    datePosted: "2 weeks ago",
    thumbnail: twitter,
    description: "Best practices for writing clean code in JavaScript.",
    likes: 4000,
    dislikes: 20,
    duration: "18:00",
    tags: ["JavaScript", "Clean Code", "Best Practices"],
    subscribers: 130000,
    comments: dummyComments
  },
  {
    title: "Building Responsive Websites with Tailwind CSS",
    channelName: "Code Academy",
    channelAvatar: avatar3,
    views: 125000,
    datePosted: "1 week ago",
    thumbnail: youtubeThumbnail,
    description: "Learn how to build responsive websites using Tailwind CSS.",
    likes: 6000,
    dislikes: 25,
    duration: "16:00",
    tags: ["Tailwind CSS", "Responsive Design", "Web Development"],
    subscribers: 160000,
    comments: [
      {
        name: "Nancy Hall",
        avatar: avatar4,
        content: "Tailwind CSS is amazing! Thanks for the tutorial.",
        timestamp: "5 days ago",
        likes: 220,
        dislikes: 3
      },
      ...(dummyComments)
    ]
  },
  {
    title: "Building a To-Do App with Redux",
    channelName: "Code Academy",
    channelAvatar: avatar4,
    views: 98000,
    datePosted: "5 days ago",
    thumbnail: discord,
    description: "Learn how to build a To-Do app using Redux.",
    likes: 4800,
    dislikes: 20,
    duration: "22:00",
    tags: ["Redux", "JavaScript", "Web Development"],
    subscribers: 160000,
    comments: dummyComments
  },
  {
    title: "Understanding Docker Containers",
    channelName: "No Boilerplate",
    channelAvatar: avatar5,
    views: 85000,
    datePosted: "2 weeks ago",
    thumbnail: instagram,
    description: "A comprehensive guide to understanding Docker containers.",
    likes: 3900,
    dislikes: 18,
    duration: "14:00",
    tags: ["Docker", "Containers", "DevOps"],
    subscribers: 130000,
    comments: [
      {
        name: "Paul Brown",
        avatar: avatar6,
        content: "Great explanation. Docker seems less intimidating now.",
        timestamp: "12 days ago",
        likes: 160,
        dislikes: 3
      },
      ...(dummyComments)
    ]
  },
  {
    title: "JavaScript Async/Await Tutorial",
    channelName: "Let's get Rusty",
    channelAvatar: avatar7,
    views: 110000,
    datePosted: "1 week ago",
    thumbnail: netflix,
    description: "Learn how to use async/await in JavaScript.",
    likes: 5600,
    dislikes: 25,
    duration: "18:00",
    tags: ["JavaScript", "Async/Await", "Programming"],
    subscribers: 100000,
    comments: dummyComments
  },
  {
    title: "Basics of Algorithms",
    channelName: "CS50",
    channelAvatar: avatar1,
    views: 220000,
    datePosted: "1 month ago",
    thumbnail: tiktok,
    description: "Introduction to algorithms and their importance.",
    likes: 12000,
    dislikes: 55,
    duration: "28:00",
    tags: ["Algorithms", "Computer Science", "CS50"],
    subscribers: 200000,
    comments: dummyComments
  },
  {
    title: "Creating a Music Playlist with JavaScript",
    channelName: "ckmobile",
    channelAvatar: avatar2,
    views: 76000,
    datePosted: "3 weeks ago",
    thumbnail: spotify,
    description: "Build a music playlist application using JavaScript.",
    likes: 3200,
    dislikes: 12,
    duration: "24:00",
    tags: ["JavaScript", "Music", "Web Development"],
    subscribers: 150000,
    comments:dummyComments
  },
  {
    title: "Introduction to Databases",
    channelName: "Neso Academy",
    channelAvatar: avatar3,
    views: 175000,
    datePosted: "2 months ago",
    thumbnail: youtubeThumbnail,
    description: "Learn the basics of databases in this introductory video.",
    likes: 9500,
    dislikes: 40,
    duration: "20:00",
    tags: ["Databases", "Computer Science", "Education"],
    subscribers: 180000,
    comments: dummyComments
  },
  {
    title: "Live Code: Building a Weather App",
    channelName: "Code Academy",
    channelAvatar: avatar4,
    views: 99000,
    datePosted: "4 days ago",
    thumbnail: discord,
    description: "Watch live as we build a weather app from scratch.",
    likes: 5200,
    dislikes: 22,
    duration: "30:00",
    tags: ["JavaScript", "Weather App", "Live Coding"],
    subscribers: 160000,
    comments: dummyComments
  },
  {
    title: "Tailwind CSS: Building a Responsive Navbar",
    channelName: "No Boilerplate",
    channelAvatar: avatar5,
    views: 70000,
    datePosted: "2 weeks ago",
    thumbnail: instagram,
    description: "Create a responsive navbar using Tailwind CSS.",
    likes: 3400,
    dislikes: 16,
    duration: "15:00",
    tags: ["Tailwind CSS", "Web Design", "Responsive"],
    subscribers: 130000,
    comments: dummyComments
  },
  {
    title: "Prayer for Stress Relief",
    channelName: "Hallow: Prayer & Meditation",
    channelAvatar: avatar6,
    views: 50000,
    datePosted: "1 week ago",
    thumbnail: netflix,
    description: "A calming prayer session for stress relief.",
    likes: 2900,
    dislikes: 10,
    duration: "12:00",
    tags: ["Prayer", "Meditation", "Stress Relief"],
    subscribers: 90000,
    comments: dummyComments
  },
  {
    title: "Building a Full-Stack App with Rust",
    channelName: "Let's get Rusty",
    channelAvatar: avatar7,
    views: 135000,
    datePosted: "2 weeks ago",
    thumbnail: spotify,
    description: "Learn how to build a full-stack application using Rust.",
    likes: 6800,
    dislikes: 27,
    duration: "40:00",
    tags: ["Rust", "Full-Stack", "Programming"],
    subscribers: 100000,
    comments: dummyComments
  }
];

// console.log(videos.length)

export { videos };
